name: CustomSuits
main: gmail.anto5710.mcp.customsuits.CustomSuits.suit.CustomSuitPlugin
description: The Special Suits.
version: 0.2.4
auther: §b[anto5710]

commands:
    cspn:
        description: §bSpawn a suit.
        usage: "§4[Usage]: §c/cspn [Type] [TargetPlayer] [Amount]" 
    csuit:
        description: §bSummon nearest suit.
        usage: "§4[Usage]: §c/csuit"
    command:
        description: §bCommand for your suits.
        usage: "§4[Usage]: §ccommad [target + <Player> / party / firework]"
    get:
        description: §bGet the This Plugin's Items.
        usage: "§4[Usage]: §cget [commander / hammer / laucner]"
    head:
        description: §bMake that player's head
        usage: "§4[Usage]: §chead / head <Player>"
    clist:
        description: §bGet the list about that topic.
        usage: "§4[Usage]: §cclist [Color / Entity]"
    
     
