name: CustomSuits
main: gmail.anto5710.mcp.customsuits.CustomSuits.CustomSuitPlugin
version: 0.1
description: 몹의 옷을 뺐어 입습니다.

commands:
    cspn:
        description: spawn a suit, cspn <type> <target> <amounts>
    csuit:
        description: summon nearest suit
    command:
        description: /command target <player>  target player   ,  /command party   summon all suits,   firework  explode all suits
    get:
        description: /get gun give gun to player , /get commander give player commander
    head:
        description: make that player's head
     
