name: CustomSuits
main: gmail.anto5710.mcp.customsuits.CustomSuits.CustomSuitPlugin
description: The Special Suits.
version: 0.6.5
api-version: 1.13
authors: [anto5710 , 02hunnam , sanseong] 

commands:
    cspn:
        description: §bSpawn a suit.
        usage: "/cspn [Type] [Amount]" 
    csuit:
        description: §bSummon nearest suit.
        usage: "/csuit"
    command:
        description: §bCommand for your suits.
        usage: "/commad [target + <Player> / party / firework]"
    get:
        description: §bGet This Plugin's Items.
        usage: "/get [commander / hammer / laucner]"
    head:
        description: §bMake that player's head
        usage: "/head / head <Player>"
    clist:
        description: §bGet the list about the topic.
        usage: "/clist [Color / Entity]"
    setcolor:
        description: §bSet the color of the ArmorType.
        usage: "/setcolor [helmet / chestplate / leggings / boots] [Color]"
    setvehicle:
        description: §bSet the EntityType of Vehicle.
        usage: "/setvehicle [Entity]"
    
    
     
